### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by eviljust** [sim0n00ps/OF-DRM#10]
After i modified the auth.json.. OF website on the browser page logs out automatically and getting "Auth failed, please check the values in auth.json are correct, press any key to exit" error on the app.

i relog again and re-edit with the latest session string on the auth.json but still getting the same error above... hmmmm

**Comment by sim0n00ps** [comment]
Make sure your user-agent is correct, always re-copy it from the browser to make sure

**Comment by eviljust** [comment]
Yes, i copied from the inspect, under network. still the same

**Comment by eviljust** [comment]
Ok, after copying again. it's working.
