### ISSUE TITLE
Virtual Device Offline

### ISSUE THREAD

**Issue by Trannerr** [sim0n00ps/OF-DRM#13]
Hey sim0n thank u for your work.

This is concerning getting 'device_client_id_blob and device_private_key', been working endlessly on it.

I can't execute the **adb exe**  because it says "device offline", correctly so since my virtual phone is never booting up when i click Play.

Lmk

**Comment by thegitdanger** [comment]
Hi bro! I'im making a telegram group about Onlyfans DRM, would you like to come?
[https://](https://t.me/onlydrm)
