### ISSUE TITLE
Exception caught: Unable to parse license

### ISSUE THREAD

**Issue by booleangit** [sim0n00ps/OF-DRM#3]
When trying to download paid posts from messages, I'll get this error:

![image](https://github.com/sim0n00ps/OF-DRM/assets/25500731/fc55a641-9fc8-4f4d-8581-98e6e625a8d1)

As you can see, the regular posts download correctly. Any idea what might be causing this?

I normally use OF-DL instead of OF-DRM, but since this specific user has so much content and I only wanted to grab my latest purchase, I decided to try this version.

**Comment by sim0n00ps** [comment]
> When trying to download paid posts from messages, I'll get this error:
> 
> ![image](https://github.com/sim0n00ps/OF-DRM/assets/25500731/fc55a641-9fc8-4f4d-8581-98e6e625a8d1)
> 
> As you can see, the regular posts download correctly. Any idea what might be causing this?
> 
> I normally use OF-DL instead of OF-DRM, but since this specific user has so much content and I only wanted to grab my latest purchase, I decided to try this version.

I'll look into it

**Comment by sim0n00ps** [comment]
Fixed it, I'll make a new release now

**Comment by booleangit** [comment]
I can confirm it now works indeed, thanks!

![image](https://github.com/sim0n00ps/OF-DRM/assets/25500731/cecd1cbc-f7f1-4be7-b58f-98c20fc2a8d7)
