### ISSUE TITLE
How to specify a download path?

### ISSUE THREAD

**Issue by harrcc31** [sim0n00ps/OF-DRM#6]
I want to specify a specific folder for downloaded videos. How can I do this?

**Comment by sim0n00ps** [comment]
You can't, this is mainly made for integrating with the same file structure digitalcriminals used in his script, you can tell the scraper where your __user_data__ folder is so it doesn't download in the same directory as the program.

**Comment by harrcc31** [comment]
Yes, this is exactly what I was looking for. Thanks!
