### ISSUE TITLE
Issues downloading paid messages

### ISSUE THREAD

**Issue by harrcc31** [sim0n00ps/OF-DRM#7]
Hi, for some reason, the scrapper is not finding any drm paid messages. And I have two that I've bought that I'm trying to download.

**Comment by Puk0** [comment]
> not finding any drm paid messages

En la versión 1.6
En las cuentas gratis no encuentra los videos pagados 
En las cuentas de paga si los encuentra
![2023-07-20_001722](https://github.com/sim0n00ps/OF-DRM/assets/138377242/ab3f5967-bb3f-4c88-8493-42ef288d25bb)

**Comment by Puk0** [comment]
También en la versión 1.5 
Solo en las cuentas de paga encuentra los videos pagado
![2023-07-20_004423](https://github.com/sim0n00ps/OF-DRM/assets/138377242/466923eb-7a41-4063-b9b5-25e8a95ca499)

**Comment by sim0n00ps** [comment]
Yeah upon looking at the code I need to change some things as I can see where it's going wrong

**Comment by sim0n00ps** [comment]
Latest release should fix Paid Posts and Messages
