### ISSUE TITLE
Need help for getting DRM key

### ISSUE THREAD

**Issue by eviljust** [sim0n00ps/OF-DRM#8]
Hi,

I followed the guide on getting the drm keys from:
https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio

C:\Users\xxxxx\Downloads\dumper-main>Python dump_keys.py
Traceback (most recent call last):
  File "C:\Users\xxxxx\Downloads\dumper-main\dump_keys.py", line 6, in <module>
    from Helpers.Device import Device
ModuleNotFoundError: No module named 'Helpers.Device'

I don't see a Device.py in the Helpers folder.

**Comment by Puk0** [comment]
¿version de python?
tienes la misma version de "frida"?
instalaste pycryptodome y protobuf?

**Comment by sim0n00ps** [comment]
You need to download the whole GitHub repo, not just dump_keys.py

**Comment by eviljust** [comment]
oh it's working for me now for the getting the drm keys part. 

But now strangely after i modified the auth.json.. OF website on the browser page logs out automatically and getting "Auth failed, please check the values in auth.json are correct, press any key to exit" error on the app.

i relog again and re-edit with the latest session id but still getting the same error above... hmmmm
