### ISSUE TITLE
Windows Defender (false?)positive?!

### ISSUE THREAD

**Issue by T3rminat0r** [sim0n00ps/OF-DRM#9]
Hi, I just now found this project, after setting up your other, yesterday... and well, Version 1.7 does cause a (false?)positive hit with windows defender for "Trojan:Win32/Sabsik.FL.B!ml" (a ransomware trojan, apparently) ... 1.6 does not, though?

**Comment by sim0n00ps** [comment]
Definitely a false positive, the program is 100% safe

**Comment by T3rminat0r** [comment]
Yea, [VirusTotal](https://www.virustotal.com/gui/file-analysis/NDVmYzA1MWMwNDIwYTAzNjQ4MTFhMjQ4NjJhZDgxN2Y6MTY5MDYzNjA4Ng==) does agree. Just Thought you should know that there is that false positive going around.
